### ISSUE TITLE
Configure JWT verification

### ISSUE THREAD

**Issue by mike-audi** [tiki/core-trail-write#129]
### Reason

Read and write access is controlled by the account service

### Description

Use access tokens created by the account service to control read and write access.

- Access should be scoped to a specific provider and user id

### Success Criteria

- [ ] JWT validation 
- [ ] Use the public keys from the account service jwks.json — inject as env vars

**Comment by ricardobrg** [comment]
The initial lambda authorizer is written in https://github.com/tiki/publish-data-receipt/. We need to move the code from there and adjust the business logic to use as the default authorizer for all our APIs.
